author:
  name: Bruno Ferreti

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "bferreti@microsofr.com"
  github: bferreti
  linkedin: bferreti

# Select which share links to show in posts
share-links-active:
  linkedin: true

theme: jekyll-theme-tactile
